name: Calculadora Saque Aniversário FGTS - CI

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - '**.gitignore'
      - '**.md'
  pull_request:
    branches:
      - develop
    paths-ignore:
      - '**.gitignore'
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.14.4'

      - name: Execute Gradle build
        run: gradle build

